version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: SoccerLC
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SoccerLC

  scrapers:
    build: .
    command: npm start
    environment:
      PGUSER: SoccerLC
      PGPASSWORD: password
      PGDATABASE: SoccerLC
      PGHOST: postgres
    links:
      - postgres
