version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: SoccerLC
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SoccerLC

  scrapers:
    build:
      context: .
      dockerfile: scrapers.Dockerfile
    command: npm start
    environment:
      PGUSER: SoccerLC
      PGPASSWORD: password
      PGDATABASE: SoccerLC
      PGHOST: postgres
    links:
      - postgres

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    command: npm start
    ports:
      - "80"
    environment:
      PGUSER: SoccerLC
      PGPASSWORD: password
      PGDATABASE: SoccerLC
      PGHOST: postgres
      VIRTUAL_HOST: soccerlc.docker
    tty: true
    depends_on:
      - postgres
    links:
      - postgres

  notifier:
    build:
      context: .
      dockerfile: notifier.Dockerfile
    command: npm start
    environment:
      PGUSER: SoccerLC
      PGPASSWORD: password
      PGDATABASE: SoccerLC
      PGHOST: postgres
    links:
      - postgres
